name: inoventory_ui
description: inoventory UI

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  dio: ^4.0.6
  intl: ^0.17.0
  openid_client: ^0.4.7
  flutter_secure_storage: ^7.0.1
  url_launcher: ^6.1.7
  jwt_decode: ^0.3.1
  flutter_web_auth: ^0.5.0
  collection: ^1.16.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  mobile_scanner: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3


flutter:
  uses-material-design: true